### PR TITLE
PM2 process manager

### PR DESCRIPTION
**Pull request by matthewberryman**

### CODE REVIEW

**Comment by matthewberryman** [comment]
@pierotofy I just thought of one small tweak while driving and added it in (the latest commit), now happy for you to review.

**Comment by pierotofy** [comment]
Changes look good (expect perhaps the config.js mention in the readme, see the discussion on #6)! Would you be able to make a pull request for the dev branch? Thanks!

**Comment by matthewberryman** [comment]
Sorry I thought I had done the config.js change in the README.md separately in this pull request, my bad. I can redo a pull request against dev but probably not until Thursday my time.

**Comment by pierotofy** [comment]
No worries! :+1:

**Comment by matthewberryman** [comment]
Will do pull request against dev branch.

**Pull request closed without merging**
