### PR TITLE
Mention use of config.js file in README.md

### PR DESCRIPTION
**Pull request by matthewberryman**
As discussed at https://github.com/pierotofy/node-OpenDroneMap/pull/5#commitcomment-18475834

### CODE REVIEW

**Comment by pierotofy** [comment]
I wonder if we should try to make config.js 100% configurable via command line parameters? I don't think it would be a good practice to modify directly config.js. What are your thoughts?

**Comment by matthewberryman** [comment]
You could but since this is a web server it wouldn't normally be started directly from the command line directly but via a startup script, like one installed by pm2, or in an environment like AWS Elastic Beanstalk or IBM BlueMix etc. For petajakarta.org we have a config file in https://GitHub.com/smart-facility/cognicity-server with a bunch of defaults and some we configure for our deployment via the config file, others we suck in to the config via environment variables in AWS Elastic Beanstalk. 

There are also a lot of logging config options as well and I'm not sure if you want to expose all of those via command line options?

**Comment by pierotofy** [comment]
Mm, I can see the problem of having too many command line arguments (perhaps especially in the future, if we keep adding more configurations). For startup scripts, you can pass command line arguments via scripts, so there's no issue there (same for environmental variables).

Perhaps a better approach could be to specify the configuration in a config.json and read that in? Then have a single command line argument that specifies the configuration (for example, node index.js --config config.json).

**Comment by matthewberryman** [comment]
I know you can pass command line arguments via startup scripts but it's a bit uglier IMHO, particularly as more configuration options are added as we've discussed.

I like your suggestion of having a config.json file that can be specified using a --config option; that argument (to the config.json file) can then be specified in the AWS Elastic Beanstalk config, or in the pm2 processes.json file (add a line "args": "--config config.json",) after #8 is merged. 

How about this: you set up the argument parameters (config and any overrides as per your existing arguments, as they can be useful in dev environments), and I can then update the PM2 processes file and also add in some notes about running on AWS in a pull request? (I could do IBM BlueMix, but I'm a bit rusty so I'd have to read up and test deployment there again).

**Comment by matthewberryman** [comment]
Hmm, just thinking (after hitting comment) that deploying (and therefore documenting) to AWS doesn't make sense until the code for distributing tasks across a cluster is in place. On that,  I suspect the best way of distributing tasks to other VMs on a cluster is via ssh (with ssh keys set up) to run the ODM run script on other VMs? There are some (unfortunately) AWS-specific ways of starting up other VMs (and then saving to a shared filesystem/s3 bucket) and tearing them down when done.

**Comment by pierotofy** [comment]
I'll work on adding a config.json loader sometimes today.

**Comment by pierotofy** [comment]
A config.json file can now be specified via command line arguments. I will close this pull request since it doesn't apply anymore. Let's open a discussion if there are further suggestions or improvements in this area.

**Pull request closed without merging**
